name: Test

on: workflow_call

permissions:
  contents: read

env:
  src_dir: hatching

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libfuzzy-dev libfuzzy2
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r tests/requirements.txt
    - name: Unit Test
      run: |
        [ ! -d "$(pwd)/tests" ] && echo "No tests found" && exit
        #export REPO_NAME=${BUILD_REPOSITORY_NAME##*/}
        python -m pytest -p no:cacheprovider --durations=10 -rsx -xsvvv --disable-warnings
